# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grn/grn.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrn/grn.proto\x12\x03grn\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x04\n\x0fPurchaseReceipt\x12\n\n\x02id\x18\x01 \x01(\t\x12\x30\n\x0c\x64\x61te_created\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rdate_modified\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12$\n\x0b\x62uying_type\x18\x04 \x01(\x0e\x32\x0f.grn.BuyingType\x12\x10\n\x08supplier\x18\x05 \x01(\t\x12\x15\n\rsupplier_name\x18\x06 \x01(\t\x12\x14\n\x0cterritory_id\x18\x07 \x01(\t\x12\x12\n\ncompany_id\x18\x08 \x01(\t\x12\x14\n\x0cposting_date\x18\t \x01(\t\x12\x14\n\x0cposting_time\x18\n \x01(\t\x12\x10\n\x08\x63urrency\x18\x0b \x01(\t\x12\x18\n\x10set_warehouse_id\x18\x0c \x01(\t\x12\x11\n\ttotal_qty\x18\r \x01(\x02\x12\x12\n\nbase_total\x18\x0e \x01(\x02\x12\x16\n\x0e\x62\x61se_net_total\x18\x0f \x01(\x02\x12\x18\n\x10transporter_name\x18\x10 \x01(\t\x12\'\n\x05items\x18\x11 \x03(\x0b\x32\x18.grn.PurchaseReceiptItem\x12\r\n\x05owner\x18\x12 \x01(\t\x12\x13\n\x0bmodified_by\x18\x13 \x01(\t\x12\x19\n\x11\x63u_invoice_number\x18\x14 \x01(\t\"\xfc\x01\n\x13PurchaseReceiptItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x11\n\titem_code\x18\x02 \x01(\t\x12\x11\n\titem_name\x18\x03 \x01(\t\x12\r\n\x05\x62rand\x18\x04 \x01(\t\x12\x15\n\ritem_group_id\x18\x05 \x01(\t\x12\x14\n\x0creceived_qty\x18\x06 \x01(\x02\x12\x0b\n\x03uom\x18\x07 \x01(\t\x12\x0c\n\x04rate\x18\x08 \x01(\x02\x12\x0e\n\x06\x61mount\x18\t \x01(\x02\x12\x12\n\nnet_amount\x18\n \x01(\x02\x12\x1b\n\x13material_request_id\x18\x0b \x01(\t\x12\x16\n\x0epurchase_order\x18\x0c \x01(\t*A\n\nBuyingType\x12\x0e\n\nPURCHASING\x10\x00\x12\x0f\n\x0bPROCUREMENT\x10\x01\x12\x12\n\x0eTrade_Purchase\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grn.grn_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BUYINGTYPE']._serialized_start=845
  _globals['_BUYINGTYPE']._serialized_end=910
  _globals['_PURCHASERECEIPT']._serialized_start=56
  _globals['_PURCHASERECEIPT']._serialized_end=588
  _globals['_PURCHASERECEIPTITEM']._serialized_start=591
  _globals['_PURCHASERECEIPTITEM']._serialized_end=843
# @@protoc_insertion_point(module_scope)
