# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock_entry/stock_entry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstock_entry/stock_entry.proto\x12\x0bstock_entry\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x03\n\nStockEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x10stock_entry_type\x18\x02 \x01(\t\x12\x1b\n\x13source_warehouse_id\x18\x03 \x01(\t\x12\x1d\n\x15source_warehouse_type\x18\x04 \x01(\t\x12\x1b\n\x13target_warehouse_id\x18\x05 \x01(\t\x12\x1d\n\x15target_warehouse_type\x18\x06 \x01(\t\x12,\n\x05items\x18\x07 \x03(\x0b\x32\x1d.stock_entry.StockEntryDetail\x12\x14\n\x0cterritory_id\x18\x08 \x01(\t\x12\x1c\n\x14total_incoming_value\x18\t \x01(\x02\x12\x1c\n\x14total_outgoing_value\x18\n \x01(\x02\x12\x0f\n\x07purpose\x18\x0b \x01(\t\x12\x0f\n\x07remarks\x18\x0c \x01(\t\x12\x30\n\x0c\x64\x61te_created\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rdate_modified\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nuser_email\x18\x0f \x01(\t\"\xed\x01\n\x10StockEntryDetail\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x11\n\titem_code\x18\x03 \x01(\t\x12\x11\n\titem_name\x18\x04 \x01(\t\x12\x15\n\ritem_group_id\x18\x05 \x01(\t\x12\x0b\n\x03qty\x18\x06 \x01(\x02\x12\x1b\n\x13source_warehouse_id\x18\x07 \x01(\t\x12\x1b\n\x13target_warehouse_id\x18\x08 \x01(\t\x12\x0b\n\x03uom\x18\t \x01(\t\x12\x11\n\tstock_uom\x18\n \x01(\t\x12\x18\n\x10item_description\x18\x0b \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_entry.stock_entry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STOCKENTRY']._serialized_start=80
  _globals['_STOCKENTRY']._serialized_end=533
  _globals['_STOCKENTRYDETAIL']._serialized_start=536
  _globals['_STOCKENTRYDETAIL']._serialized_end=773
# @@protoc_insertion_point(module_scope)
