# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item_price/item_price.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bitem_price/item_price.proto\x12\nitem_price\"\xdc\x01\n\tItemPrice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x0b\n\x03uom\x18\x03 \x01(\t\x12\x11\n\titem_name\x18\x04 \x01(\t\x12\x12\n\nprice_list\x18\x05 \x01(\t\x12\x10\n\x08supplier\x18\x06 \x01(\t\x12\x0e\n\x06\x62uying\x18\x07 \x01(\x08\x12\x0f\n\x07selling\x18\x08 \x01(\x08\x12\x10\n\x08\x63urrency\x18\t \x01(\t\x12\x17\n\x0fprice_list_rate\x18\n \x01(\x02\x12\x0c\n\x04note\x18\x0b \x01(\t\x12\x12\n\nvalid_from\x18\x0c \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_price.item_price_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ITEMPRICE']._serialized_start=44
  _globals['_ITEMPRICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
