# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item/item.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fitem/item.proto\x12\x04item\"\xef\x02\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\titem_code\x18\x02 \x01(\t\x12\x11\n\titem_name\x18\x03 \x01(\t\x12\x15\n\ritem_group_id\x18\x04 \x01(\t\x12\x16\n\x0emaintain_stock\x18\x05 \x01(\x08\x12\x16\n\x0evaluation_rate\x18\x06 \x01(\x01\x12\x11\n\tstock_uom\x18\x07 \x01(\t\x12\x17\n\x0fweight_per_unit\x18\x08 \x01(\x02\x12\x12\n\nweight_uom\x18\t \x01(\t\x12\x0e\n\x06length\x18\n \x01(\t\x12\r\n\x05width\x18\x0b \x01(\t\x12\x0e\n\x06height\x18\x0c \x01(\t\x12\x10\n\x08\x64isabled\x18\r \x01(\x08\x12\"\n\x04uoms\x18\x0e \x03(\x0b\x32\x14.item.Item.UomsEntry\x12\x1c\n\x05taxes\x18\x0f \x03(\x0b\x32\r.item.ItemTax\x1a+\n\tUomsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x85\x01\n\x07ItemTax\x12\x1c\n\x14item_tax_template_id\x18\x01 \x01(\t\x12\x14\n\x0ctax_category\x18\x02 \x01(\t\x12\x12\n\nvalid_from\x18\x03 \x01(\t\x12\x18\n\x10minimum_net_rate\x18\x04 \x01(\x02\x12\x18\n\x10maximum_net_rate\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item.item_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEM_UOMSENTRY._options = None
  _ITEM_UOMSENTRY._serialized_options = b'8\001'
  _globals['_ITEM']._serialized_start=26
  _globals['_ITEM']._serialized_end=393
  _globals['_ITEM_UOMSENTRY']._serialized_start=350
  _globals['_ITEM_UOMSENTRY']._serialized_end=393
  _globals['_ITEMTAX']._serialized_start=396
  _globals['_ITEMTAX']._serialized_end=529
# @@protoc_insertion_point(module_scope)
